### PR TITLE
Assets/Enable..Log..Write -> Preferences/VSCode: Unity 4.x support

### PR DESCRIPTION
**Pull request by Taugeshtu**
Switched toggles from Menu.SetChecked to PreferenceItem, effectively making them work in Unity 4.x.

### CODE REVIEW

**Comment by Taugeshtu** [comment]
Forgot the screenshot:
screen shot 2015-09-11 at 15 45 14

**Comment by reapazor** [comment]
For a while I wanted to put the settings in the preferences (and had something similar) but opted initially for the menu approach. I'll stir over this for a few days --- I'm not sure all the hooks used are there in 4.x ... can I assume you've checked that?

**Comment by Taugeshtu** [comment]
So far I've checked:
Open project - opens correct context
Open file (while context is opened in VSCode) - check
Open file on line through double-click in console log - check
Launch file overwrite - check
Logging plugin actions - check
Enable/disable - check

Debugging sort of works (hangs Unity up tight), but that's to be expected.
So yeah, it should work on 4.x just as well with just these changes.

**Comment by cra0zy** [comment]
Will this be merged any time soon? I am asking this because of 2 things:
1) Unity on Linux menu not being checkable yet
2) I want to submit a PR for Linux support which will modify same lines of code and create merge conflicts for one of the PRs

**Comment by reapazor** [comment]
I'll probably do the merge of this today, I need to notify the right people about updating the documentation at Microsoft.

**Comment by reapazor** [comment]
I've done a few changes to it, just to keep things a little cleaner.

**Pull request merged**
