### PR TITLE
Check for update IF

### PR DESCRIPTION
**Pull request by Allough**
Check for updates only if "Automatic Updates" is checked in the unity preferences.

### CODE REVIEW

**Comment by aaulia** [comment]
+1 very annoying.

**Comment by reapazor** [comment]
Must of lost that at some point :)

**Comment by Allough** [comment]
Thanks for the plugin Matthew! Loving VS Code so far :)

**Comment by indieforger** [comment]
Is that bug there again? Every time I click play btn I got annoying popup "Checking for updates..." that hangs there for 3 - 5 min. It really kills me and makes the VS Code practically unusable. Is there way to switch it off somehow?

**Comment by Allough** [comment]
Latest commit (6 days ago) has the correct code.

As long as you have the latest version, and have Automatic Updates turned off, it should be working.

If you don't want to download the latest from Github, you can check line 256 in the VSCode.cs.
 It is inside your project folder, and the line should look like this:
if (DateTime.Now >= targetDate && AutomaticUpdates)

**Pull request merged**
